### ISSUE TITLE
Global Pathfinding Enhancements Tracker

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/tasks#12]
Enhancements to our new project over Raye.

- [ ] Decide whether to create new codebase or continue building off of [raye-global-pathfinding](https://github.com/UBCSailbot/raye-global-pathfinding)
    - If migrating
        - Update issue to match #9
        - Create issue equivalent to #10
    - If continuing
        - Revert repo name to global-pathfinding
        - Convert tasks to issues
    - Either way, transfer issue to the active global pathfinding repository

### Enhancements
- [ ] Integrate with NET remote transciever
    - [ ] Run on demand
    - [ ] Sync with NET
- [ ] Run locally in sailbot_workspace
    - [ ] Create mock and manually specified global path planner
        - Raye equivalent: [`MOCK_global_planner.py`](https://github.com/UBCSailbot/raye-local-pathfinding/blob/master/python/MOCK_global_planner.py)
- [ ]  Set geographical limits on valid waypoints: is this necessary? Discuss with MECH
