### ISSUE TITLE
Pathfinding Tasks Tracker

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/tasks#13]
For general pathfinding tasks that don't need issues.

### Meetings
- [ ] Discuss new project with past pathfinding members: Tyler, Kieran
- [ ] Talk with NET about mocks and sensor filtering
- [ ] Talk with NET about global pathfinding x remote transceiver integration

### Research
- [ ] Determine whether we need object detection, and whether it is feasible
    - Revisit once basic functionality is migrated/implemented

### Other
- [ ] Upload research papers related to Raye to Google Drive
    - [ ] In repositories
    - [ ] Paper that we wrote
