### ISSUE TITLE
Local Pathfinding Design Specification

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/tasks#19]
Design spec: https://ubcsailbot.atlassian.net/l/cp/h11Sjcze

### Purpose
To clearly define the responsibilities, goals, and design rationale of local pathfinding.

### 0.1 Milestone
- [x] #11 @patrick-5546 
- [ ] Discuss with MECH about data collection behavior @Krithik1 
- [x] Write overview section @patrick-5546 

### 0.3 Milestone
- [ ] Figure out what stats need to be sent to website
- [ ] Path planners research and evaluation @Krithik1

**Comment by patrick-5546** [comment]
Closed in favour of https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/1798701376/Winter+2023+Timeline#PATH:-Local-Pathfinding

**Comment by patrick-5546** [comment]
Closed in favour of https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/1798701376/Winter+2023+Timeline#PATH:-Local-Pathfinding
