### ISSUE TITLE
Website Design Specification

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/tasks#20]
Design spec: https://ubcsailbot.atlassian.net/l/cp/1FD69kcd

### Purpose
To clearly define the responsibilities, goals, and design rationale of the website.

### 0.1 Milestone
- [x] Talk with NET about website x remote transceiver integration
- [ ] Explore saildrone websites, see if there is anything we can takeaway @dk1702 
- [x] Add detail, flesh out ideas in overview section @jamenkaye @dk1702 
    - [x] Functionality
    - [x] Audiences, and how their use cases are addressed
    - [x] Tradeoffs / design considerations

### 0.3 Milestone
- [ ] Split website into pages
- [ ] How you want to organize the data in database @jamenkaye 
- [ ] Explore potential solutions
    - [ ] Grafana
- [ ] netCDF @dk1702

**Comment by patrick-5546** [comment]
Closed in favour of https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/1798701376/Winter+2023+Timeline#PATH:-Website

**Comment by patrick-5546** [comment]
Closed in favour of https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/1798701376/Winter+2023+Timeline#PATH:-Website
