### ISSUE TITLE
Figure out subteam repository CI

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/tasks#22]
### Purpose
Doesn't really make sense for CI to be run in sailbot_workspace, should be in the subteams' repositories.

### Changes
Can explore this in network_systems, the only new project subteam repo created so far. I'm thinking that we can move the lint and test CI from sailbot_workspace to network_systems. One complexity will be using the `.devcontainer/Dockerfile` image in sailbot_workspace. Then we can create a starter workflow from what we learned so that it will be easy to add CI in future subteam repositories.

### To Do
- [x] Implement CI in network_systems
- [x] Make CI from sailbot_workspace run weekly (regression tests)
- [x] Create starter workflow in .github

### Resources
- https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization

**Comment by patrick-5546** [comment]
@hhenry01 If you want to start development on network_systems this would be a good issue to address first

**Comment by hhenry01** [comment]
Resolved when these two PRs are merged: https://github.com/UBCSailbot/network_systems/pull/6, https://github.com/UBCSailbot/sailbot_workspace/pull/60

## How it was done
### Part 1: Network Systems Repo
- I copied the `.github/` folder from sailbot_workspace into the repo except for the `actions/` folder.
- I edited the workflow yaml files to first clone sailbot_workspace, and then clone network_systems into the src/ directory
  - VCS cannot be used here because it cannot dynamically target the current branch that someone is trying to merge 
### Part 2: Sailbot Workspace Repo
- Removed `.github/workflows`
- Edited the scripts so that VCS is disabled when running CI for the reason stated before

## Questions
1. I'm not sure what the `dependabot.yml` and `release.yml` file found under `.github/` do, so I left them in both.

**Comment by patrick-5546** [comment]
> I'm not sure what the dependabot.yml and release.yml file found under .github/ do, so I left them in both.

- Dependabot automatically creates PR's when there is a new release of a GitHub action we use
- release.yml is used to customize [automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)
